import { FaRegEdit, FaTrashAlt, FaUserCog, FaTasks, FaThLarge, FaChartBar, FaUserTie } from "react-icons/fa";
import { FaUserTag, FaChalkboardUser, FaSquare } from "react-icons/fa6";
import { TbCancel, TbClockExclamation } from "react-icons/tb";
import { TfiPrinter } from "react-icons/tfi";
import { RiFileAddLine } from "react-icons/ri";
import { VscTasklist } from "react-icons/vsc";
import { SlActionUndo, SlLike, SlDislike } from "react-icons/sl";
import { MdOutlineRadioButtonUnchecked } from "react-icons/md";
import { WiMoonAltFirstQuarter } from "react-icons/wi";
import { BiTask, BiTaskX } from "react-icons/bi";
import { LuFolderCheck } from "react-icons/lu";
import { FcOvertime, FcLeave } from "react-icons/fc";
import { IoFlag } from "react-icons/io5";
import { ImBlocked } from "react-icons/im";

export const SvgEdit = (props) => <FaRegEdit {...props} />;
export const SvgTrash = (props) => <FaTrashAlt {...props} />;
export const SvgCancel = (props) => <TbCancel {...props} />;
export const SvgPrinter = (props) => <TfiPrinter {...props} />;
export const SvgAdd = (props) => <RiFileAddLine {...props} />;
export const SvgRetroceder = (props) => <SlActionUndo  {...props} />;
export const SvgResponsavel = (props) => <FaUserTie {...props} />;
export const SvgRevisor = (props) => <FaChalkboardUser {...props} />;
export const SvgTramitador = (props) => <FaUserTag {...props} />;
export const SvgAFazer = (props) => <MdOutlineRadioButtonUnchecked {...props} />;
export const SvgEmProgresso = (props) => <WiMoonAltFirstQuarter {...props} />;
export const SvgAuardandoRevisao = (props) => <TbClockExclamation {...props} />;
export const SvgTarefaOK = (props) => <SlLike  {...props} />;
export const SvgTarefaFalha = (props) => <SlDislike {...props} />;
export const SvgAtivarTarefa = (props) => <BiTask {...props} />;
export const SvgDesativarTarefa = (props) => <BiTaskX {...props} />;
export const SvgTarefaFinalizada = (props) => <LuFolderCheck {...props} />;
export const SvgFlag = (props) => <FaSquare {...props} />;
export const SvgPrazoTarefaAcabando = (props) => <FcOvertime {...props} />;
export const SvgPrazoTarefaAcabou = (props) => <FcLeave {...props} />;
export const SvgBloqueado = (props) => <ImBlocked {...props} />;

export const SvgEDashboard = (props) => <FaChartBar {...props} />;
export const SvgECards = (props) => <FaThLarge {...props} />;
export const SvgETarefas = (props) => <VscTasklist {...props} />;
export const SvgETramites = (props) => <FaTasks {...props} />;
export const SvgEUsuarios = (props) => <FaUserCog {...props} />;
export const SvgEFlags = (props) => <IoFlag {...props} />;